elasticsearch:
    host: localhost:9200
    indexes:
        - duo
        - schoolvo
        - onderwijsinspectie
        - ocw
    types_per_index:
        duo:
            - vo_school
            - vo_branch
            - vo_board
            - po_school
            - po_branch
            - po_board
            - pao_collaboration
            - mbo_board
            - mbo_institution
            - ho_board
            - ho_institution
        schoolvo:
            - vo_branch
        onderwijsinspectie:
            - vo_branch
            - po_branch
        ocw:
            - po_branch